### ISSUE TITLE
Variable x0 is not using 

### ISSUE THREAD

**Issue by RUI-LONG** [jephianlin/outreach#1]
I'm sure it's a small issue to fix. 
In outreach/Sage4HS/Calculus.ipynb cell 26, x0 is not using in that cell.
#4 Should be 
quo = (f.subs(x = x0+h) - f.subs(x = x0)) / h

![x0_is_not_using](https://user-images.githubusercontent.com/25581309/77282520-21f21a00-6d05-11ea-9c94-0a8b514de3ba.png)

p.s. If you please, please let me know what is "quo" 's meaning.

**Comment by jephianlin** [comment]
Thank you so much.  The issue has been fixed.  

For 'quo', I am thinking of quotient, the quotient form in the definition of the derivative.
